-
    hostname: '192.168.10.11'
    port: 22
    username: "root"
    password: "123456"
-
    hostname: '192.168.10.12'
    port: 22
    username: "root"
    password: "123456"
-
    hostname: '192.168.10.13'
    port: 22
    username: "root"
    password: "123456"